### ISSUE TITLE
Always use var when defining a JS variable 

### ISSUE THREAD

**Issue by jwld** [fac18/khol#70]
https://github.com/fac18/khol/blob/a845bad2e29f8f9213b6a1223e4009c0ea374755/scripts.js#L3

When you don't use `var`, JavaScript does some funky stuff and will make this variable as globally-scoped (☠️) as possible - basically not behaviour you want. When you use `var` it will limit the variable to whatever scope it's defined in. See [here](https://stackoverflow.com/questions/2485423/is-using-var-to-declare-variables-optional).

**Comment by nikkesan** [comment]
Great point! resolved on a2141ce
