### ISSUE TITLE
Use classes for CSS, and ids for JS

### ISSUE THREAD

**Issue by jwld** [fac18/khol#76]
https://github.com/fac18/khol/blob/a845bad2e29f8f9213b6a1223e4009c0ea374755/style.css#L268-L270

This isn't a strict rule by any means, but it's quite a common pattern.

When you're reading an `html` file it's just quite nice to know that the classes are for CSS and the ids are for JS (at least as much as possible).

Classes are generally more suited to css because you can re-use them, while ids are a safer option for JS when you're trying to target one element in particular.

In some rare situations you might have to use a class to target multiple elements from JS however.

**Comment by nikkesan** [comment]
Thanks for the reminder, much appreciated!

Resolved on SHA a2141ce
